import unittest
import pandas as pd
import os
import sys
import tempfile
from io import BytesIO

# Add repo root to path
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from server import app

# Check if legacy module exists
try:
    from legacy.excel_agent import ExcelAgent
    LEGACY_AVAILABLE = True
except ImportError:
    LEGACY_AVAILABLE = False

@unittest.skipUnless(LEGACY_AVAILABLE, "Legacy ExcelAgent not available")
class TestExcelAgent(unittest.TestCase):
    def setUp(self):
        self.agent = ExcelAgent()

    def create_messy_excel(self):
        data = {
            'Region': ['North', 'South', 'East', 'West', 'North'],
            'Sales': [100, 200, 'oops', 400, 500],
            'Date': ['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04', '2023-01-05']
        }
        df = pd.DataFrame(data)
        output = BytesIO()
        with pd.ExcelWriter(output, engine='openpyxl') as writer:
            pd.DataFrame([['Report Title'], ['Generated by AI']]).to_excel(writer, sheet_name='Sheet1', index=False, header=False)
            df.to_excel(writer, sheet_name='Sheet1', startrow=3, index=False)
        output.seek(0)
        return output.read()

    def test_messy_data_classification(self):
        content = self.create_messy_excel()
        steps, df = self.agent.analyze_file(content)

        classification_log = next((s for s in steps if s['step'] == 'Column Analysis'), None)
        self.assertIsNotNone(classification_log)

        # Verify Sales is in Metrics
        # Log string: "Dimensions: ['Region', 'Date'], Metrics: ['Sales']"
        details = classification_log['details']
        self.assertIn("'Sales'", details.split("Metrics:")[1])
        self.assertNotIn("'Sales'", details.split("Dimensions:")[1].split("Metrics:")[0])

class TestServer(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()
        self.client.testing = True

    def test_index_page(self):
        response = self.client.get('/')
        self.assertEqual(response.status_code, 200)
        # Check for current title
        self.assertIn(b'DataIngest AI', response.data)

if __name__ == '__main__':
    unittest.main()
